// <auto-generated />
namespace TA_ASP_Zoknik.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SeedKolcsonzok : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedKolcsonzok));
        
        string IMigrationMetadata.Id
        {
            get { return "202204042001599_SeedKolcsonzok"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
